DROP PROCEDURE IF EXISTS STP_TM_PERSONAS
GO

CREATE PROCEDURE STP_TM_PERSONAS(
	@ID INT = NULL,
	@PRIMER_NOMBRE VARCHAR(50) = NULL,
	@SEGUNDO_NOMBRE VARCHAR(50) = NULL,
	@PRIMER_APELLIDO VARCHAR(50) = NULL,
	@SEGUNDO_APELLIDO VARCHAR(50) = NULL,
	@NUMERO_DOCUMENTO VARCHAR(50) = NULL,
	@EMAIL VARCHAR(100) = NULL,
	@CELULAR VARCHAR(15) = NULL,
	@EDAD INT = NULL,
	@ESTADO BIT = NULL,
	@ID_TIPO_DOCUMENTO INT = NULL,
	@ID_GENERO INT = NULL,
	@ID_USUARIO INT = NULL,
	@OPERACION TINYINT = NULL
)
AS
BEGIN

	SET NOCOUNT ON;
---------------------
-- INSERTAR
---------------------
	IF @OPERACION = 0
	BEGIN
		
		INSERT INTO
			TM_PERSONAS
		(
			PRIMER_NOMBRE,
			SEGUNDO_NOMBRE,
			PRIMER_APELLIDO,
			SEGUNDO_APELLIDO,
			NUMERO_DOCUMENTO,
			EMAIL,
			CELULAR,
			EDAD,
			ESTADO,
			ID_TIPO_DOCUMENTO,
			ID_GENERO,
			ID_USUARIO
		)
		VALUES
		(
			@PRIMER_NOMBRE,
			@SEGUNDO_NOMBRE,
			@PRIMER_APELLIDO,
			@SEGUNDO_APELLIDO,
			@NUMERO_DOCUMENTO,
			@EMAIL,
			@CELULAR,
			@EDAD,
			1,
			@ID_TIPO_DOCUMENTO,
			@ID_GENERO,
			@ID_USUARIO
		)

		SELECT SCOPE_IDENTITY();

	END

--------------------
-- ACTUALIZAR
--------------------
	IF @OPERACION = 1
	BEGIN
		
		UPDATE
			TM_PERSONAS
		SET 
			PRIMER_NOMBRE = @PRIMER_NOMBRE,
			SEGUNDO_NOMBRE = @SEGUNDO_NOMBRE,
			PRIMER_APELLIDO = @PRIMER_APELLIDO,
			SEGUNDO_APELLIDO = @SEGUNDO_APELLIDO,
			NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO,
			EMAIL = @EMAIL,
			CELULAR = @CELULAR,
			EDAD = @EDAD,
			ID_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO,
			--ID_USUARIO = @ID_USUARIO,
			ID_GENERO = @ID_GENERO
		WHERE
			ID = @ID
	END


--------------------
-- ELIMINAR
--------------------
	IF @OPERACION = 2
	BEGIN
		
		DELETE FROM
			TM_PERSONAS
		WHERE 
			ID = @ID

	END

--------------------
-- SELECCIONAR UNO
--------------------
	
	IF @OPERACION = 3
	BEGIN
		
		SELECT
			ID,
			PRIMER_NOMBRE,
			SEGUNDO_NOMBRE,
			PRIMER_APELLIDO,
			SEGUNDO_APELLIDO,
			NUMERO_DOCUMENTO,
			EMAIL,
			CELULAR,
			EDAD,
			ESTADO,
			ID_TIPO_DOCUMENTO,
			ID_GENERO,
			ID_USUARIO
		FROM 
			TM_PERSONAS
		WHERE 
			ID = @ID

	END

---------------------
-- SELECCIONAR TODOS
---------------------

	IF @OPERACION = 4
	BEGIN
		
		SELECT
			ID,
			PRIMER_NOMBRE,
			SEGUNDO_NOMBRE,
			PRIMER_APELLIDO,
			SEGUNDO_APELLIDO,
			NUMERO_DOCUMENTO,
			EMAIL,
			CELULAR,
			EDAD,
			ESTADO,
			ID_TIPO_DOCUMENTO,
			ID_GENERO,
			ID_USUARIO
		FROM 
			TM_PERSONAS

	END


----------------------------
-- VALIDAR PERSONA - USUARIO
----------------------------
	IF @OPERACION = 5
	BEGIN
		
		--Se verifica si el usuario tiene sus datos personales registrados.
		DECLARE @PERSONA INT = (
			SELECT TOP 1
				ID
			FROM 
				TM_PERSONAS
			WHERE ID_USUARIO = @ID_USUARIO
		)

		SELECT TOP 1
			CASE WHEN @PERSONA IS NOT NULL
			THEN
				CONVERT(BIT, 1)
			ELSE
				CONVERT(BIT, 0)
			END AS ExistePersona,
			@PERSONA AS IdPersona		
	END
END