DROP PROCEDURE IF EXISTS STP_ENFERMEDADES_PERSONAS
GO

CREATE PROCEDURE STP_ENFERMEDADES_PERSONAS(
	@ID INT = NULL,	
	@FECHA_DIAGNOSTICO DATETIME = NULL,	
	@ID_PERSONA INT = NULL,
	@ID_ENFERMEDAD INT = NULL,
	@ID_ESTADO INT = NULL,
	@OPERACION TINYINT = NULL
)
AS
BEGIN

	SET NOCOUNT ON;
---------------------
-- INSERTAR
---------------------
	IF @OPERACION = 0
	BEGIN
		
		INSERT INTO
			TM_ENFERMEDADES_PERSONAS
		(
			FECHA_DIAGNOSTICO,
			ID_PERSONA,
			ID_ENFERMEDAD,
			ID_ESTADO
		)
		VALUES
		(
			@FECHA_DIAGNOSTICO,
			@ID_PERSONA,
			@ID_ENFERMEDAD,
			1
		)

		SELECT SCOPE_IDENTITY();

	END

--------------------
-- ACTUALIZAR
--------------------
	IF @OPERACION = 1
	BEGIN
		
		UPDATE
			TM_ENFERMEDADES_PERSONAS
		SET 
			FECHA_DIAGNOSTICO = @FECHA_DIAGNOSTICO,
			ID_PERSONA = @ID_PERSONA,
			ID_ENFERMEDAD = @ID_ENFERMEDAD,
			ID_ESTADO = @ID_ESTADO
		WHERE
			ID = @ID
	END


--------------------
-- ELIMINAR
--------------------
	IF @OPERACION = 2
	BEGIN
		
		DELETE FROM
			TM_ENFERMEDADES_PERSONAS
		WHERE 
			ID = @ID

	END

--------------------
-- SELECCIONAR UNO
--------------------
	
	IF @OPERACION = 3
	BEGIN
		
		SELECT
			ID,
			FECHA_DIAGNOSTICO,
			ID_PERSONA,
			ID_ENFERMEDAD,
			ID_ESTADO
		FROM 
			TM_ENFERMEDADES_PERSONAS
		WHERE 
			ID = @ID

	END

---------------------
-- SELECCIONAR TODOS
---------------------

	IF @OPERACION = 4
	BEGIN
		
		SELECT
			ID,
			FECHA_DIAGNOSTICO,
			ID_PERSONA,
			ID_ENFERMEDAD,
			ID_ESTADO
		FROM 
			TM_ENFERMEDADES_PERSONAS

	END

---------------------
-- SELECCIONAR TODOS POR PERSONA
---------------------

	IF @OPERACION = 5
	BEGIN
		
		SELECT
			TM_ENFERMEDADES_PERSONAS.ID,
			TM_ENFERMEDADES_PERSONAS.FECHA_DIAGNOSTICO,
			TM_ENFERMEDADES_PERSONAS.ID_PERSONA,
			TM_ENFERMEDADES_PERSONAS.ID_ENFERMEDAD,
			TP_ENFERMEDADES.DESCRIPCION AS NOMBRE_ENFERMEDAD,
			TM_ENFERMEDADES_PERSONAS.ID_ESTADO,
			TR_ESTADOS_ENFERMEDADES.DESCRIPCION AS NOMBRE_ESTADO
		FROM 
			TM_ENFERMEDADES_PERSONAS
		INNER JOIN
			TP_ENFERMEDADES
		ON
			TP_ENFERMEDADES.ID = TM_ENFERMEDADES_PERSONAS.ID_ENFERMEDAD
		INNER JOIN
			TR_ESTADOS_ENFERMEDADES
		ON
			TR_ESTADOS_ENFERMEDADES.ID = TM_ENFERMEDADES_PERSONAS.ID_ESTADO
		WHERE
			ID_PERSONA = @ID_PERSONA
	END
END