DROP PROCEDURE IF EXISTS STP_TM_EXAMENES_PERSONAS
GO

CREATE PROCEDURE STP_TM_EXAMENES_PERSONAS(
	@ID INT = NULL,	
	@INFORMACION VARCHAR(MAX) = NULL,
	@FECHA_EXAMEN DATETIME = NULL,
	@FECHA_RESULTADOS DATETIME = NULL,
	@ID_PERSONA INT = NULL,	
	@OPERACION TINYINT = NULL
)
AS
BEGIN

	SET NOCOUNT ON;
---------------------
-- INSERTAR
---------------------
	IF @OPERACION = 0
	BEGIN
		
		INSERT INTO
			TM_EXAMENES_PERSONAS
		(
			INFORMACION,
			FECHA_EXAMEN,
			FECHA_RESULTADOS,
			ID_PERSONA			
		)
		VALUES
		(
			@INFORMACION,
			@FECHA_EXAMEN,
			@FECHA_RESULTADOS,
			@ID_PERSONA			
		)

		SELECT SCOPE_IDENTITY();

	END

--------------------
-- ACTUALIZAR
--------------------
	IF @OPERACION = 1
	BEGIN
		
		UPDATE
			TM_EXAMENES_PERSONAS
		SET 
			INFORMACION = @INFORMACION,
			ID_PERSONA = @ID_PERSONA,
			FECHA_EXAMEN = @FECHA_EXAMEN,			
			FECHA_RESULTADOS = @FECHA_RESULTADOS
		WHERE
			ID = @ID
	END


--------------------
-- ELIMINAR
--------------------
	IF @OPERACION = 2
	BEGIN
		
		DELETE FROM
			TM_EXAMENES_PERSONAS
		WHERE 
			ID = @ID

	END

--------------------
-- SELECCIONAR UNO
--------------------
	
	IF @OPERACION = 3
	BEGIN
		
		SELECT
			ID,
			INFORMACION,
			ID_PERSONA,
			FECHA_EXAMEN,			
			FECHA_RESULTADOS
		FROM 
			TM_EXAMENES_PERSONAS
		WHERE 
			ID = @ID

	END

---------------------
-- SELECCIONAR TODOS
---------------------

	IF @OPERACION = 4
	BEGIN
		
		SELECT
			ID,
			INFORMACION,
			ID_PERSONA,
			FECHA_EXAMEN,			
			FECHA_RESULTADOS
		FROM 
			TM_EXAMENES_PERSONAS

	END

---------------------
-- SELECCIONAR TODOS POR PERSONA
---------------------

	IF @OPERACION = 5
	BEGIN
		
		SELECT
			TM_EXAMENES_PERSONAS.ID,
			TM_EXAMENES_PERSONAS.INFORMACION,
			TM_EXAMENES_PERSONAS.ID_PERSONA,
			TM_EXAMENES_PERSONAS.FECHA_EXAMEN,
			TM_EXAMENES_PERSONAS.FECHA_RESULTADOS
		FROM 
			TM_EXAMENES_PERSONAS
		WHERE
			ID_PERSONA = @ID_PERSONA
	END
END